<?php
$piqes_slider_sc = piqes_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $piqes_slider_sc ) && strpos( $piqes_slider_sc, '[' ) !== false && strpos( $piqes_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider">
	<?php
		// Add anchor
		$piqes_anchor_icon = piqes_get_theme_option( 'front_page_title_anchor_icon' );
		$piqes_anchor_text = piqes_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $piqes_anchor_icon ) || ! empty( $piqes_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $piqes_anchor_icon ) ? ' icon="' . esc_attr( $piqes_anchor_icon ) . '"' : '' )
									. ( ! empty( $piqes_anchor_text ) ? ' title="' . esc_attr( $piqes_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $piqes_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$piqes_scheme = piqes_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $piqes_scheme ) && ! piqes_is_inherit( $piqes_scheme ) ) {
			echo ' scheme_' . esc_attr( $piqes_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( piqes_get_theme_option( 'front_page_title_paddings' ) );
		?>
		"
		<?php
		$piqes_css      = '';
		$piqes_bg_image = piqes_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $piqes_bg_image ) ) {
			$piqes_css .= 'background-image: url(' . esc_url( piqes_get_attachment_url( $piqes_bg_image ) ) . ');';
		}
		if ( ! empty( $piqes_css ) ) {
			echo ' style="' . esc_attr( $piqes_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$piqes_anchor_icon = piqes_get_theme_option( 'front_page_title_anchor_icon' );
		$piqes_anchor_text = piqes_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $piqes_anchor_icon ) || ! empty( $piqes_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $piqes_anchor_icon ) ? ' icon="' . esc_attr( $piqes_anchor_icon ) . '"' : '' )
									. ( ! empty( $piqes_anchor_text ) ? ' title="' . esc_attr( $piqes_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( piqes_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' piqes-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$piqes_css      = '';
			$piqes_bg_mask  = piqes_get_theme_option( 'front_page_title_bg_mask' );
			$piqes_bg_color_type = piqes_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $piqes_bg_color_type ) {
				$piqes_bg_color = piqes_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $piqes_bg_color_type ) {
				$piqes_bg_color = piqes_get_scheme_color( 'bg_color', $piqes_scheme );
			} else {
				$piqes_bg_color = '';
			}
			if ( ! empty( $piqes_bg_color ) && $piqes_bg_mask > 0 ) {
				$piqes_css .= 'background-color: ' . esc_attr(
					1 == $piqes_bg_mask ? $piqes_bg_color : piqes_hex2rgba( $piqes_bg_color, $piqes_bg_mask )
				) . ';';
			}
			if ( ! empty( $piqes_css ) ) {
				echo ' style="' . esc_attr( $piqes_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$piqes_caption = piqes_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $piqes_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $piqes_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post( $piqes_caption ); ?></h1>
					<?php
				}

				// Description (text)
				$piqes_description = piqes_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $piqes_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $piqes_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post( wpautop( $piqes_description ) ); ?></div>
					<?php
				}

				// Buttons
				if ( piqes_get_theme_option( 'front_page_title_button1_link' ) != '' || piqes_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						piqes_show_layout( piqes_customizer_partial_refresh_front_page_title_button1_link() );
						piqes_show_layout( piqes_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
